### ISSUE TITLE
GB/T 12345 编码问题

### ISSUE THREAD

**Issue by NightFurySL2001** [mrhso/IshisashiEncoding#5]
我有几个关于 GB/T 12345 的问题：

1. 如果参考 Unicode 旧文件（http://glyph.iso10646hk.net/download/GB12345.TXT ），一些字形并不是对应“繁体”而是根据字形选择。请问有什么选择码位的见解吗？
2. 如果参考其他“争”的汉字，应该是选用“⺈”头而不是“爫”头的字形，但是“静” (30-18 或 0x3E32) 却是选用 U+975C `靜` 而不是 U+9759 `静`.

**Comment by mrhso** [comment]
1. 我不是很明白这个问题。
2. 表错了，感谢汇报。
![image](https://github.com/mrhso/IshisashiEncoding/assets/13294467/83aad85d-bb39-44e8-9cfb-cd3d1852eb3d)

**Comment by NightFurySL2001** [comment]
比如说按仓库字表选用`争鳧隷𨻶`，但是按照 Unicode 旧文件（http://glyph.iso10646hk.net/download/GB12345.TXT ）是`爭鳬隸隙`。是完全按照按照 GB/T 12345 内的字形选择？

**Comment by mrhso** [comment]
> 是完全按照按照 GB/T 12345 内的字形选择？

是的。
需要注意的是那个旧文件大抵是按 G1 源算的，而 G1 源本身是 [Pseudo-GB/T 12345](https://ccjktype.fonts.adobe.com/2018/01/standards-102.html)。
我没有检查全表，所以不清楚是否还有类似的错误。

**Comment by NightFurySL2001** [comment]
好的，另了解到 Unicode 旧文件很可能包含 ad-hoc extension （GB 12052-89 内 71-89 至 71-94，72-01 至 72-88 的汉字）。
https://ccjktype.fonts.adobe.com/wp-content/uploads/2014/12/gb12052-uni.txt
